rename anvil_eater0.png anvil_eater.png
rename bad_apple0.png bad_apple.png
rename block_of_flesh0.png block_of_flesh.png
rename bloodcurdle0.png bloodcurdle.png
rename brimmeth0.png brimmeth.png
rename canker0.png canker.png
rename cannibal0.png cannibal.png
rename cerebroid0.png cerebroid.png
rename cirrus_archer0.png cirrus_archer.png
rename citroid0.png citroid.png
rename clay_maul0.png clay_maul.png
rename cursed_tome0.png cursed_tome.png
rename dead_crusader0.png dead_crusader.png
rename dead_vele0.png dead_vele.png
rename deadhound0.png deadhound.png
rename discarded_sword0.png discarded_sword.png
rename dune_rider0.png dune_rider.png
rename embers0.png embers.png
rename fallen_summoner0.png fallen_summoner.png
rename fictos0.png fictos.png
rename fire_maiden0.png fire_maiden.png
rename gargoyle0.png gargoyle.png
rename gastric_sprout0.png gastric_sprout.png
rename giant_pumpkin_piece_active0.png giant_pumpkin_piece_active.png
rename giant_pumpkin_piece_inactive0.png giant_pumpkin_piece_inactive.png
rename giant_scorpion0.png giant_scorpion.png
rename goblin_champion0.png goblin_champion.png
rename grass_gulper0.png grass_gulper.png
rename gravedigger0.png gravedigger.png
rename guest0.png guest.png
rename headless_chicken0.png headless_chicken.png
rename headless_horse0.png headless_horse.png
rename hellifish0.png hellifish.png
rename hiveminded0.png hiveminded.png
rename hobgoblin0.png hobgoblin.png
rename hollow_ent0.png hollow_ent.png
rename indactma0.png indactma.png
rename irican0.png irican.png
rename iriditite0.png iriditite.png
rename ivywake0.png ivywake.png
rename karkaros0.png karkaros.png
rename land_leech0.png land_leech.png
rename land_sludge0.png land_sludge.png
rename lustrebone0.png lustrebone.png
rename megapod0.png megapod.png
rename melon_head0.png melon_head.png
rename meltdown0.png meltdown.png
rename mist_wraith0.png mist_wraith.png
rename moghes0.png moghes.png
rename mootaur0.png mootaur.png
rename murmur0.png murmur.png
rename obsidian_disaster0.png obsidian_disaster.png
rename ocula0.png ocula.png
rename phantas0.png phantas.png
rename polar_tyrant0.png polar_tyrant.png
rename pyrodactyl0.png pyrodactyl.png
rename quakemight0.png quakemight.png
rename quicksand0.png quicksand.png
rename rags0.png rags.png
rename rampage0.png rampage.png
rename ramwolf0.png ramwolf.png
rename redstone_rusher0.png redstone_rusher.png
rename rockram0.png rockram.png
rename rootling0.png rootling.png
rename rotten_jack0.png rotten_jack.png
rename runimon0.png runimon.png
rename rupture_bug0.png rupture_bug.png
rename screamer0.png screamer.png
rename severed0.png severed.png
rename sgouger0.png sgouger.png
rename shellbit0.png shellbit.png
rename shroombie0.png shroombie.png
rename shulker_warrior0.png shulker_warrior.png
rename sonaga0.png sonaga.png
rename spin_jack0.png spin_jack.png
rename spitblot0.png spitblot.png
rename sting_face0.png sting_face.png
rename stone_warrior0.png stone_warrior.png
rename studbark0.png studbark.png
rename tall_mimic0.png tall_mimic.png
rename terra_terror0.png terra_terror.png
rename torchure0.png torchure.png
rename tusoch0.png tusoch.png
rename undead_coral0.png undead_coral.png
rename undead_livestock0.png undead_livestock.png
rename wood_crab0.png wood_crab.png