const shelf = document.querySelector('[data-holds="shelf"]');

[
	{ "name": "10294 LEGO Titanic", "tag": "LEGO", "image": "10294.webp" },
	{ "name": "11900 LEGO City Brickmaster", "tag": "LEGO", "image": "11900.webp" },
	{ "name": "21344 LEGO Icons The Orient Express Train", "tag": "LEGO", "image": "21344.webp" },
	{ "name": "42032 LEGO Technic Compact Tracked Loader", "tag": "LEGO", "image": "42032.webp" },
	{ "name": "42038 LEGO Technic Arctic Truck", "tag": "LEGO", "image": "42038.webp" },
	{ "name": "42055 LEGO Technic Bucket Wheel Excavator", "tag": "LEGO", "image": "42055.webp" },
	{ "name": "42100 LEGO Technic Liebherr R 9800 Excavator", "tag": "LEGO", "image": "42100.webp" },
	{ "name": "42146 LEGO Technic Liebherr Crawler Crane LR 13000", "tag": "LEGO", "image": "42146.webp" },
	{ "name": "4427 LEGO City Fire ATV", "tag": "LEGO", "image": "4427.webp" },
	{ "name": "4430 LEGO City Fire Transporter", "tag": "LEGO", "image": "4430.webp" },
	{ "name": "4628 LEGO Fun With Bricks", "tag": "LEGO", "image": "4628.webp" },
	{ "name": "4365 Safari Building Set", "tag": "LEGO", "image": "4635.webp" },
	{ "name": "60034 LEGO Arctic Helicrane", "tag": "LEGO", "image": "60034.webp" },
	{ "name": "60052 LEGO City Cargo Train", "tag": "LEGO", "image": "60052.webp" },
	{ "name": "60095 City Deep Sea Exploration Vessel", "tag": "LEGO", "image": "60095.webp" },
	{ "name": "60197 LEGO City Passenger Train", "tag": "LEGO", "image": "60197.webp" },
	{ "name": "60198 LEGO City Cargo Train", "tag": "LEGO", "image": "60198.webp" },
	{ "name": "60336 LEGO City Freight Train", "tag": "LEGO", "image": "60336.webp" },
	{ "name": "60337 LEGO City Express Passenger Train", "tag": "LEGO", "image": "60337.webp" },
	{ "name": "60470 LEGO City Explorers' Arctic Polar Express Train", "tag": "LEGO", "image": "60470.webp" },
	{ "name": "6912 LEGO Creator Super Soarer", "tag": "LEGO", "image": "6912.webp" },
	{ "name": "70167 AGENTS Invizable Gold Getaway", "tag": "LEGO", "image": "70167.webp" },
	{ "name": "70700 LEGO Galaxy Squad Space Swarmer", "tag": "LEGO", "image": "70700.webp" },
	{ "name": "70805 LEGO Movie Trash Chomper", "tag": "LEGO", "image": "70805.webp" },
	{ "name": "75909 LEGO Speed Champions Mclaren P1", "tag": "LEGO", "image": "75909.webp" },
	{ "name": "76321 LEGO Super Heroes Marvel Spider-Man vs. Doc Ock Subway Train Scene", "tag": "LEGO", "image": "76321.webp" },
	{ "name": "7938 LEGO City Passenger Train", "tag": "LEGO", "image": "7938.webp" },
	{ "name": "7939 LEGO City Cargo Train", "tag": "LEGO", "image": "7939.webp" },
	{ "name": "80704 LEGO Movie Ice Cream Machine", "tag": "LEGO", "image": "80704.webp" },
	{ "name": "9391 LEGO Technic Crawler Crane", "tag": "LEGO", "image": "9391.webp" },
	{ "name": "Twin Mill 2014", "tag": "Hotwheels", "image": "hotwheels_000001.webp" },
	{ "name": "Lamborghini Sesto Elemento", "tag": "Hotwheels", "image": "hotwheels_000002.webp" },
	{ "name": "'66 Chevy Nova", "tag": "Hotwheels", "image": "hotwheels_000003.webp" },
	{ "name": "Lamborghini Gallardo LP 570-4 Superleggera", "tag": "Hotwheels", "image": "hotwheels_000004.webp" },
	{ "name": "2021 Toyota GR Supra", "tag": "Hotwheels", "image": "hotwheels_000005.webp" },
	{ "name": "Toyota GR86 Cup", "tag": "Hotwheels", "image": "hotwheels_000006.webp" },
	{ "name": "2005 Aston Martin DB9", "tag": "Hotwheels", "image": "hotwheels_000007.webp" },
	{ "name": "Alfa Romeo GTV6 3.0", "tag": "Hotwheels", "image": "hotwheels_000008.webp" },
	{ "name": "'20 Toyota GR Supra", "tag": "Hotwheels", "image": "hotwheels_000009.webp" },
	{ "name": "McLaren P1", "tag": "Hotwheels", "image": "hotwheels_000010.webp" },
	{ "name": "Back to the Future Time Machine - 1955", "tag": "Hotwheels", "image": "hotwheels_000011.webp" },
	{ "name": "Back to the Future Time Machine", "tag": "Hotwheels", "image": "hotwheels_000012.webp" },
	{ "name": "2016 BMW M2", "tag": "Hotwheels", "image": "hotwheels_000013.webp" },
	{ "name": "'89 Mercedes-Benz 560 SEC AMG", "tag": "Hotwheels", "image": "hotwheels_000014.webp" },
	{ "name": "Dodge Viper SRT10 ACR", "tag": "Hotwheels", "image": "hotwheels_000015.webp" },
	{ "name": "'69 Mercury Cougar Eliminator", "tag": "Hotwheels", "image": "hotwheels_000016.webp" },
	{ "name": "Porsche 934 Turbo RSR", "tag": "Hotwheels", "image": "hotwheels_000017.webp" },
	{ "name": "Lamborghini Sesto Elemento", "tag": "Hotwheels", "image": "hotwheels_000018.webp" },
	{ "name": "VW Bug", "tag": "Hotwheels", "image": "hotwheels_000019.webp" },
	{ "name": "Porsche 935", "tag": "Hotwheels", "image": "hotwheels_000020.webp" },
	{ "name": "Pandem Subaru BRZ", "tag": "Hotwheels", "image": "hotwheels_000021.webp" },
	{ "name": "2008 Lancer Evolution", "tag": "Hotwheels", "image": "hotwheels_000022.webp" },
	{ "name": "1988 Ford T-Bird", "tag": "Hotwheels", "image": "hotwheels_000023.webp" },
	{ "name": "Mercedes-Benz E 36 AMG", "tag": "Hotwheels", "image": "hotwheels_000024.webp" },
	{ "name": "Custom '18 Ford Mustang GT", "tag": "Hotwheels", "image": "hotwheels_000025.webp" },
	{ "name": "'98 Honda Prelude", "tag": "Hotwheels", "image": "hotwheels_000026.webp" },
	{ "name": "DeLorean Alpha5", "tag": "Hotwheels", "image": "hotwheels_000027.webp" },
	{ "name": "Lotus Cortina", "tag": "Hotwheels", "image": "hotwheels_000028.webp" },
	{ "name": "Visa Cash App RB F1 Team", "tag": "Hotwheels", "image": "hotwheels_000029.webp" },
	{ "name": "2012 Volkswagen Beetle", "tag": "Hotwheels", "image": "hotwheels_000030.webp" },
	{ "name": "Bugatti Veyron", "tag": "Hotwheels", "image": "hotwheels_000031.webp" },
	{ "name": "Nissan Maxima Drift Car", "tag": "Hotwheels", "image": "hotwheels_000032.webp" },
	{ "name": "Nissan Skyline GT-R (BCNR33)", "tag": "Hotwheels", "image": "hotwheels_000033.webp" },
	{ "name": "Lamborghini Gallardo LP 570-4 Superleggera", "tag": "Hotwheels", "image": "hotwheels_000034.webp" },
	{ "name": "Nissan Skyline GT-R (BCNR33)", "tag": "Hotwheels", "image": "hotwheels_000035.webp" },
	{ "name": "Jaguar Lightweight E-Type", "tag": "Hotwheels", "image": "hotwheels_000036.webp" },
	{ "name": "'18 COPO Camaro SS", "tag": "Hotwheels", "image": "hotwheels_000037.webp" },
	{ "name": "BWT Alpine F1 Team", "tag": "Hotwheels", "image": "hotwheels_000038.webp" },
	{ "name": "'16 Bugatti Chiron", "tag": "Hotwheels", "image": "hotwheels_000039.webp" },
	{ "name": "McLaren Formula 1 Team", "tag": "Hotwheels", "image": "hotwheels_000040.webp" },
	{ "name": "Ford Mustang Dark Horse", "tag": "Hotwheels", "image": "hotwheels_000041.webp" },
	{ "name": "Dimachinni Veloce", "tag": "Hotwheels", "image": "hotwheels_000042.webp" },
	{ "name": "2020 Koenigsegg Jesko", "tag": "Hotwheels", "image": "hotwheels_000043.webp" },
	{ "name": "'84 Pontiac Firebird", "tag": "Hotwheels", "image": "hotwheels_000044.webp" },
	{ "name": "Lamborghini Sián FKP 37", "tag": "Hotwheels", "image": "hotwheels_000045.webp" },
	{ "name": "BMW 635 CSi", "tag": "Hotwheels", "image": "hotwheels_000046.webp" },
	{ "name": "Aston Martin Vulcan", "tag": "Hotwheels", "image": "hotwheels_000047.webp" },
	{ "name": "'71 Datsun Bluebird 510 Wagon", "tag": "Hotwheels", "image": "hotwheels_000048.webp" },
	{ "name": "'82 Toyota Supra", "tag": "Hotwheels", "image": "hotwheels_000049.webp" },
	{ "name": "Mazda 787B", "tag": "Hotwheels", "image": "hotwheels_000050.webp" },
	{ "name": "Subaru WRX STI", "tag": "Hotwheels", "image": "hotwheels_000051.webp" },
	{ "name": "DMC DeLorean", "tag": "Hotwheels", "image": "hotwheels_000052.webp" },
	{ "name": "Nissan 300ZX Twin Turbo", "tag": "Hotwheels", "image": "hotwheels_000053.webp" },
	{ "name": "LB-WORKS McLaren 720S", "tag": "Hotwheels", "image": "hotwheels_000054.webp" },
	{ "name": "MoneyGram Haas F1 Team", "tag": "Hotwheels", "image": "hotwheels_000055.webp" },
	{ "name": "Lamborghini Huracán LP 620-2 Super Trofeo", "tag": "Hotwheels", "image": "hotwheels_000056.webp" },
	{ "name": "'70 Chevy Camaro RS", "tag": "Hotwheels", "image": "hotwheels_000057.webp" },
	{ "name": "McLaren F1 GTR", "tag": "Hotwheels", "image": "hotwheels_000058.webp" },
	{ "name": "2013 SRT Viper", "tag": "Hotwheels", "image": "hotwheels_000059.webp" },
	{ "name": "'17 Ford GT", "tag": "Hotwheels", "image": "hotwheels_000060.webp" },
	{ "name": "Bugatti Veyron", "tag": "Hotwheels", "image": "hotwheels_000061.webp" },
	{ "name": "Renault Sport R.S. 01", "tag": "Hotwheels", "image": "hotwheels_000062.webp" },
	{ "name": "'66 Ford 427 Fairlane", "tag": "Hotwheels", "image": "hotwheels_000063.webp" },
	{ "name": "Ford GT-40", "tag": "Hotwheels", "image": "hotwheels_000064.webp" },
	{ "name": "Maserati Shamal", "tag": "Hotwheels", "image": "hotwheels_000065.webp" },
	{ "name": "2016 Ford GT Race", "tag": "Hotwheels", "image": "hotwheels_000066.webp" },
	{ "name": "Honda S2000", "tag": "Hotwheels", "image": "hotwheels_000067.webp" },
	{ "name": "Pagani Huayra", "tag": "Hotwheels", "image": "hotwheels_000068.webp" },
	{ "name": "1973 Chevy Camaro", "tag": "Hotwheels", "image": "hotwheels_000069.webp" },
	{ "name": "KICK Sauber F1 Team", "tag": "Hotwheels", "image": "hotwheels_000070.webp" },
	{ "name": "McLaren Solus GT", "tag": "Hotwheels", "image": "hotwheels_000071.webp" },
	{ "name": "Ford Mustang Dark Horse", "tag": "Hotwheels", "image": "hotwheels_000072.webp" },
	{ "name": "Nissan 370Z", "tag": "Hotwheels", "image": "hotwheels_000073.webp" },
	{ "name": "Honda S2000", "tag": "Hotwheels", "image": "hotwheels_000074.webp" },
	{ "name": "'71 Lamborghini Miura SV", "tag": "Hotwheels", "image": "hotwheels_000075.webp" },
	{ "name": "Gordon Murray Automotive T.50s", "tag": "Hotwheels", "image": "hotwheels_000076.webp" },
	{ "name": "1998 Subaru Impreza 22B STi-Version", "tag": "Hotwheels", "image": "hotwheels_000077.webp" },
	{ "name": "Lamborghini Huracán Sterrato", "tag": "Hotwheels", "image": "hotwheels_000078.webp" },
	{ "name": "Minecart", "tag": "Hotwheels", "image": "hotwheels_000079.webp" },
	{ "name": "2016 Ford GT Race", "tag": "Hotwheels", "image": "hotwheels_000080.webp" },
	{ "name": "Honda Civic Si", "tag": "Hotwheels", "image": "hotwheels_000081.webp" },
	{ "name": "'17 Acura NSX", "tag": "Hotwheels", "image": "hotwheels_000082.webp" },
	{ "name": "Lamborghini Huracán LP 610-4", "tag": "Hotwheels", "image": "hotwheels_000083.webp" },
	{ "name": "Audi 90 quattro", "tag": "Hotwheels", "image": "hotwheels_000084.webp" },
	{ "name": "Lamborghini Aventador LP 700-4", "tag": "Hotwheels", "image": "hotwheels_000085.webp" },
	{ "name": "Bugatti Bolide", "tag": "Hotwheels", "image": "hotwheels_000086.webp" },
	{ "name": "Koenigsegg Gemera", "tag": "Hotwheels", "image": "hotwheels_000087.webp" },
	{ "name": "'69 Ford Mustang Boss 302", "tag": "Hotwheels", "image": "hotwheels_000088.webp" },
	{ "name": "'66 Buick Riviera", "tag": "Hotwheels", "image": "hotwheels_000089.webp" },
	{ "name": "Porsche 911 Carrera RS 2.7", "tag": "Hotwheels", "image": "hotwheels_000090.webp" },
	{ "name": "Lamborghini Sián FKP 37", "tag": "Hotwheels", "image": "hotwheels_000091.webp" },
	{ "name": "'67 Porsche 911 R", "tag": "Hotwheels", "image": "hotwheels_000092.webp" },
	{ "name": "'92 BMW M3", "tag": "Hotwheels", "image": "hotwheels_000093.webp" },
	{ "name": "2024 Ford Mustang RTR Spec 5-FD", "tag": "Hotwheels", "image": "hotwheels_000094.webp" },
	{ "name": "'87 Ford Sierra Cosworth", "tag": "Hotwheels", "image": "hotwheels_000095.webp" },
	{ "name": "Bugatti Bolide", "tag": "Hotwheels", "image": "hotwheels_000096.webp" },
	{ "name": "Renault Sport R.S. 01", "tag": "Hotwheels", "image": "hotwheels_000097.webp" },
	{ "name": "W Motors Lykan HyperSport", "tag": "Hotwheels", "image": "hotwheels_000098.webp" },
	{ "name": "LB-Silhouette WORKS GT Nissan 35GT-RR VER.2", "tag": "Hotwheels", "image": "hotwheels_000099.webp" },
	{ "name": "Pagani Utopia", "tag": "Hotwheels", "image": "hotwheels_000100.webp" },
	{ "name": "2020 Koenigsegg Jesko", "tag": "Hotwheels", "image": "hotwheels_000101.webp" },
	{ "name": "Ford GT", "tag": "Hotwheels", "image": "hotwheels_000102.webp" },
	{ "name": "Porsche 904 Carrera GTS", "tag": "Hotwheels", "image": "hotwheels_000103.webp" },
	{ "name": "Porsche 911 Rallye", "tag": "Hotwheels", "image": "hotwheels_000104.webp" },
	{ "name": "Peugeot 9X8 Hypercar", "tag": "Hotwheels", "image": "hotwheels_000105.webp" },
	{ "name": "Proton Saga", "tag": "Hotwheels", "image": "hotwheels_000106.webp" },
	{ "name": "HW Ultimate T-Rex Transporter", "tag": "Hotwheels", "image": "hotwheels_000107.webp" },
	{ "name": "'98 Subaru Impreza 22B STi-Version", "tag": "Hotwheels", "image": "hotwheels_000108.webp" },
	{ "name": "BMW M1 Procar", "tag": "Hotwheels", "image": "hotwheels_000109.webp" },
	{ "name": "Lamborghini Huracán Sterrato", "tag": "Hotwheels", "image": "hotwheels_000110.webp" },
	{ "name": "Mazda 787B", "tag": "Hotwheels", "image": "hotwheels_000111.webp" },
	{ "name": "2018 Bentley Continental GT3", "tag": "Hotwheels", "image": "hotwheels_000112.webp" },
	{ "name": "Mazda 323 GTR", "tag": "Hotwheels", "image": "hotwheels_000113.webp" },
	{ "name": "2001 BMW M5", "tag": "Hotwheels", "image": "hotwheels_000114.webp" },
	{ "name": "BMW M1", "tag": "Hotwheels", "image": "hotwheels_000115.webp" },
	{ "name": "BMW M4", "tag": "Hotwheels", "image": "hotwheels_000116.webp" },
	{ "name": "2021 BMW M5", "tag": "Hotwheels", "image": "hotwheels_000117.webp" },
	{ "name": "'73 Pontiac Firebird", "tag": "Hotwheels", "image": "hotwheels_000118.webp" },
	{ "name": "Porsche 917 LH", "tag": "Hotwheels", "image": "hotwheels_000119.webp" },
	{ "name": "Mad Mike Mazda RX-3 Wagon", "tag": "Hotwheels", "image": "hotwheels_000120.webp" },
	{ "name": "Mercedes-Benz 500 E", "tag": "Hotwheels", "image": "hotwheels_000121.webp" },
	{ "name": "Shelby Cobra Daytona Coupe", "tag": "Hotwheels", "image": "hotwheels_000122.webp" },
	{ "name": "'73 Volvo 142 GL", "tag": "Hotwheels", "image": "hotwheels_000123.webp" },
	{ "name": "Koenigsegg CCXR", "tag": "Hotwheels", "image": "hotwheels_000124.webp" },
	{ "name": "Lancer Evolution IX", "tag": "Hotwheels", "image": "hotwheels_000125.webp" },
	{ "name": "Datsun 240Z Custom", "tag": "Hotwheels", "image": "hotwheels_000126.webp" },
	{ "name": "'81 Camaro", "tag": "Hotwheels", "image": "hotwheels_000127.webp" },
	{ "name": "'70 Toyota Celica", "tag": "Hotwheels", "image": "hotwheels_000128.webp" },
	{ "name": "1971 Nissan Skyline H/T 2000 GT-R", "tag": "Hotwheels", "image": "hotwheels_000129.webp" },
	{ "name": "'82 Toyota Supra", "tag": "Hotwheels", "image": "hotwheels_000130.webp" },
	{ "name": "Nissan Skyline HT 2000GT-X", "tag": "Hotwheels", "image": "hotwheels_000131.webp" },
	{ "name": "Custom '01 Acura Integra GSR", "tag": "Hotwheels", "image": "hotwheels_000132.webp" },
	{ "name": "'91 Mazda MX-5 Miata", "tag": "Hotwheels", "image": "hotwheels_000133.webp" },
	{ "name": "Honda Civic Si", "tag": "Hotwheels", "image": "hotwheels_000134.webp" },
	{ "name": "'71 Datsun 510", "tag": "Hotwheels", "image": "hotwheels_000135.webp" },
	{ "name": "Custom Kia EV6", "tag": "Hotwheels", "image": "hotwheels_000136.webp" },
	{ "name": "HW Ultimate T-Rex Transporter", "tag": "Hotwheels", "image": "hotwheels_000137.webp" },
	{ "name": "'68 Plymouth Barracuda Formula S", "tag": "Hotwheels", "image": "hotwheels_000138.webp" },
	{ "name": "'70 Dodge Charger RT", "tag": "Hotwheels", "image": "hotwheels_000139.webp" },
	{ "name": "1966 Chevrolet Impala", "tag": "Hotwheels", "image": "hotwheels_000140.webp" },
	{ "name": "Nissan Silvia (S13)", "tag": "Hotwheels", "image": "hotwheels_000141.webp" },
	{ "name": "Porsche 911 GT3 RS", "tag": "Hotwheels", "image": "hotwheels_000142.webp" },
	{ "name": "'70 Ford Escort RS1600", "tag": "Hotwheels", "image": "hotwheels_000143.webp" },
	{ "name": "'88 Honda CR-X", "tag": "Hotwheels", "image": "hotwheels_000144.webp" },
	{ "name": "BMW i8 Roadster", "tag": "Hotwheels", "image": "hotwheels_000145.webp" },
	{ "name": "McLaren P1", "tag": "Hotwheels", "image": "hotwheels_000146.webp" },
	{ "name": "'17 Acura NSX", "tag": "Hotwheels", "image": "hotwheels_000147.webp" },
	{ "name": "Porsche Panamera Turbo S E-Hybrid Sport Turismo", "tag": "Hotwheels", "image": "hotwheels_000148.webp" },
	{ "name": "1956 Corvette", "tag": "Hotwheels", "image": "hotwheels_000149.webp" },
	{ "name": "Pagani Zonda R", "tag": "Hotwheels", "image": "hotwheels_000150.webp" },
	{ "name": "Ford Mustang GTD", "tag": "Hotwheels", "image": "hotwheels_000151.webp" },
	{ "name": "1967 El Camino", "tag": "Hotwheels", "image": "hotwheels_000152.webp" },
	{ "name": "'82 Toyota Supra", "tag": "Hotwheels", "image": "hotwheels_000153.webp" },
	{ "name": "Dodge Viper RT/10", "tag": "Hotwheels", "image": "hotwheels_000154.webp" },
	{ "name": "'87 Buick Regal GNX", "tag": "Hotwheels", "image": "hotwheels_000155.webp" },
	{ "name": "'89 Porsche 944 Turbo", "tag": "Hotwheels", "image": "hotwheels_000156.webp" },
	{ "name": "'83 Chevy Silverado", "tag": "Hotwheels", "image": "hotwheels_000157.webp" },
	{ "name": "Volkswagen Golf Mk2", "tag": "Hotwheels", "image": "hotwheels_000158.webp" },
	{ "name": "BMW M3 Race", "tag": "Hotwheels", "image": "hotwheels_000159.webp" },
	{ "name": "Nissan Skyline GT-R (R32)", "tag": "Hotwheels", "image": "hotwheels_000160.webp" },
	{ "name": "'94 Audi Avant RS2", "tag": "Hotwheels", "image": "hotwheels_000161.webp" },
	{ "name": "Porsche 356 Outlaw", "tag": "Hotwheels", "image": "hotwheels_000162.webp" },
	{ "name": "'65 Pontiac GTO", "tag": "Hotwheels", "image": "hotwheels_000163.webp" },
	{ "name": "'81 Toyota Starlet KP61", "tag": "Hotwheels", "image": "hotwheels_000164.webp" },
	{ "name": "BMW 507", "tag": "Hotwheels", "image": "hotwheels_000165.webp" },
	{ "name": "Mercedes-Benz 190 E 2.5-16", "tag": "Hotwheels", "image": "hotwheels_000166.webp" },
	{ "name": "Audi RS 5 Coupe", "tag": "Hotwheels", "image": "hotwheels_000167.webp" },
	{ "name": "Alfa Romeo GTV6 30", "tag": "Hotwheels", "image": "hotwheels_000168.webp" },
	{ "name": "Volkswagen Golf Mk7", "tag": "Hotwheels", "image": "hotwheels_000169.webp" },
	{ "name": "1996 Porsche 911 Carrera", "tag": "Hotwheels", "image": "hotwheels_000170.webp" },
	{ "name": "'89 Mazda Savanna RX-7 FC3S", "tag": "Hotwheels", "image": "hotwheels_000171.webp" },
	{ "name": "Volkswagen T1-GTR", "tag": "Hotwheels", "image": "hotwheels_000172.webp" },
	{ "name": "2018 Bentley Continental GT3", "tag": "Hotwheels", "image": "hotwheels_000173.webp" },
	{ "name": "Nissan Skyline GT-R (BNR32)", "tag": "Hotwheels", "image": "hotwheels_000174.webp" },
	{ "name": "Porsche 917KH", "tag": "Hotwheels", "image": "hotwheels_000175.webp" },
	{ "name": "LaFerrari", "tag": "Hotwheels", "image": "hotwheels_000176.webp" },
	{ "name": "Aston Martin Vulcan", "tag": "Hotwheels", "image": "hotwheels_000177.webp" },
	{ "name": "Ferrari SF90 Stradale", "tag": "Hotwheels", "image": "hotwheels_000178.webp" },
	{ "name": "'17 Ford GT", "tag": "Hotwheels", "image": "hotwheels_000179.webp" },
	{ "name": "Lamborghini Huracán LP 610-4", "tag": "Hotwheels", "image": "hotwheels_000180.webp" },
	{ "name": "Lotus Evija", "tag": "Hotwheels", "image": "hotwheels_000181.webp" },
	{ "name": "'69 COPO Corvette", "tag": "Hotwheels", "image": "hotwheels_000182.webp" },
	{ "name": "Porsche 911 Turbo Cabriolet", "tag": "Hotwheels", "image": "hotwheels_000183.webp" },
	{ "name": "McLaren Speedtail", "tag": "Hotwheels", "image": "hotwheels_000184.webp" },
	{ "name": "'96 Nissan 180SX Type X", "tag": "Hotwheels", "image": "hotwheels_000185.webp" },
	{ "name": "Mitsubishi Lancer Evolution VI", "tag": "Hotwheels", "image": "hotwheels_000186.webp" },
	{ "name": "'95 Toyota Celica GT-Four", "tag": "Hotwheels", "image": "hotwheels_000187.webp" },
	{ "name": "'92 Honda Civic EG", "tag": "Hotwheels", "image": "hotwheels_000188.webp" },
	{ "name": "VW Bug", "tag": "Hotwheels", "image": "hotwheels_000189.webp" },
	{ "name": "Alfa Romeo Giulia TI Super", "tag": "Hotwheels", "image": "hotwheels_000190.webp" },
	{ "name": "Mazda RX-3", "tag": "Hotwheels", "image": "hotwheels_000191.webp" },
	{ "name": "'95 Mazda RX-7", "tag": "Hotwheels", "image": "hotwheels_000192.webp" },
	{ "name": "Mercedes-Benz 500 E", "tag": "Hotwheels", "image": "hotwheels_000193.webp" },
	{ "name": "2018 Honda Civic Type R", "tag": "Hotwheels", "image": "hotwheels_000194.webp" },
	{ "name": "2018 Honda Civic Type R", "tag": "Hotwheels", "image": "hotwheels_000195.webp" },
	{ "name": "Nissan 240SX (S14)", "tag": "Hotwheels", "image": "hotwheels_000196.webp" },
	{ "name": "Nissan Silvia (S15)", "tag": "Hotwheels", "image": "hotwheels_000197.webp" },
	{ "name": "Bugatti Bolide", "tag": "Hotwheels", "image": "hotwheels_000198.webp" },
	{ "name": "Lamborghini Countach LP 5000 QV", "tag": "Hotwheels", "image": "hotwheels_000199.webp" },
	{ "name": "Dodge Charge SRT Hellcat Widebody", "tag": "Hotwheels", "image": "hotwheels_000200.webp" },
	{ "name": "Toyota 2000GT", "tag": "Hotwheels", "image": "hotwheels_000201.webp" },
	{ "name": "'87 Ford Sierra Cosworth", "tag": "Hotwheels", "image": "hotwheels_000202.webp" },
	{ "name": "1990 Mercedes-Benz 190 R 2.5-16 Evolution II", "tag": "Hotwheels", "image": "hotwheels_000203.webp" },
	{ "name": "Aston Martin Vanquish", "tag": "Hotwheels", "image": "hotwheels_000204.webp" },
	{ "name": "Acura NSX GT3", "tag": "Hotwheels", "image": "hotwheels_000205.webp" },
	{ "name": "Koenigsegg Agera R", "tag": "Hotwheels", "image": "hotwheels_000206.webp" },
	{ "name": "2020 Dodge Charger Hellcat", "tag": "Hotwheels", "image": "hotwheels_000207.webp" },
	{ "name": "Lamborghini Gallardo LP 570-4 Superleggera", "tag": "Hotwheels", "image": "hotwheels_000208.webp" },
	{ "name": "'71 AMC Javelin", "tag": "Hotwheels", "image": "hotwheels_000209.webp" },
	{ "name": "AMC Rebel Machine", "tag": "Hotwheels", "image": "hotwheels_000210.webp" },
	{ "name": "Nissan 350Z Custom", "tag": "Hotwheels", "image": "hotwheels_000211.webp" },
	{ "name": "Nissan Silvia (S15)", "tag": "Hotwheels", "image": "hotwheels_000212.webp" },
	{ "name": "1996 Nissan 180 SX Type X", "tag": "Hotwheels", "image": "hotwheels_000213.webp" },
	{ "name": "Toyota AE86 Sprinter Trueno", "tag": "Hotwheels", "image": "hotwheels_000214.webp" },
	{ "name": "Toyota Soarer", "tag": "Hotwheels", "image": "hotwheels_000215.webp" },
	{ "name": "Toyota 2000GT", "tag": "Hotwheels", "image": "hotwheels_000216.webp" },
	{ "name": "Toyota Supra", "tag": "Hotwheels", "image": "hotwheels_000217.webp" },
	{ "name": "Lancia Delta Integrale", "tag": "Hotwheels", "image": "hotwheels_000218.webp" },
	{ "name": "'91 BMW M5", "tag": "Hotwheels", "image": "hotwheels_000219.webp" },
	{ "name": "Toyota Land Cruiser FJ43", "tag": "Hotwheels", "image": "hotwheels_000220.webp" },
	{ "name": "Alfa Romeo GTV6 3.0", "tag": "Hotwheels", "image": "hotwheels_000221.webp" },
	{ "name": "Meyers Manx", "tag": "Hotwheels", "image": "hotwheels_000222.webp" },
	{ "name": "2008 Mercedes-Benz CLK 63 AMG Black Series", "tag": "Hotwheels", "image": "hotwheels_000223.webp" },
	{ "name": "Maserati MC20", "tag": "Hotwheels", "image": "hotwheels_000224.webp" },
	{ "name": "2024 Toyota Tacoma TRD Pro", "tag": "Hotwheels", "image": "hotwheels_000225.webp" },
	{ "name": "'98 Toyota Altezza", "tag": "Hotwheels", "image": "hotwheels_000226.webp" },
	{ "name": "'17 Ford GT", "tag": "Hotwheels", "image": "hotwheels_000227.webp" },
	{ "name": "'80 Mercedes-Benz 500 SLC Rallye", "tag": "Hotwheels", "image": "hotwheels_000228.webp" },
	{ "name": "'95 Lamborghini Diablo SV", "tag": "Hotwheels", "image": "hotwheels_000229.webp" },
	{ "name": "Mitsubishi Pajero Evolution", "tag": "Hotwheels", "image": "hotwheels_000230.webp" },
	{ "name": "'77 Pontiac Firebird TA", "tag": "Hotwheels", "image": "hotwheels_000231.webp" },
	{ "name": "'94 Nissan Primera", "tag": "Hotwheels", "image": "hotwheels_000232.webp" },
	{ "name": "Ford GT", "tag": "Hotwheels", "image": "hotwheels_000233.webp" },
	{ "name": "Nissan Laurel C33", "tag": "Hotwheels", "image": "hotwheels_000234.webp" },
	{ "name": "'75 Ford Bronco", "tag": "Hotwheels", "image": "hotwheels_000235.webp" },
	{ "name": "Lamborghini Temerario", "tag": "Hotwheels", "image": "hotwheels_000236.webp" },
	{ "name": "Ford RS200", "tag": "Hotwheels", "image": "hotwheels_000237.webp" },
	{ "name": "Mercedes-Benz E 36 AMG", "tag": "Hotwheels", "image": "hotwheels_000238.webp" },
	{ "name": "Mazda MX-5 Miata", "tag": "Hotwheels", "image": "hotwheels_000239.webp" },
	{ "name": "Subaru BRZ", "tag": "Hotwheels", "image": "hotwheels_000240.webp" },
	{ "name": "Datsun 240Z", "tag": "Hotwheels", "image": "hotwheels_000241.webp" },
	{ "name": "Toyota GR86 Cup", "tag": "Hotwheels", "image": "hotwheels_000242.webp" },
	{ "name": "Corvette Grand Sport", "tag": "Hotwheels", "image": "hotwheels_000243.webp" },
	{ "name": "'70 Dodge Hemi Challenger", "tag": "Hotwheels", "image": "hotwheels_000244.webp" },
	{ "name": "Super Twin Mill", "tag": "Hotwheels", "image": "hotwheels_000245.webp" },
	{ "name": "'87 Audi quattro", "tag": "Hotwheels", "image": "hotwheels_000246.webp" },
	{ "name": "'17 Acura NSX", "tag": "Hotwheels", "image": "hotwheels_000247.webp" },
	{ "name": "Aston Martin Vantage GTE", "tag": "Hotwheels", "image": "hotwheels_000248.webp" },
	{ "name": "Volkswagen Jetta MK3", "tag": "Hotwheels", "image": "hotwheels_000249.webp" },
	{ "name": "Volkswagen ID R", "tag": "Hotwheels", "image": "hotwheels_000250.webp" },
	{ "name": "Volvo EC220 Excavator", "tag": "Maisto", "image": "maisto_000001.webp" },
	{ "name": "Maisto Mini Working Machines Bobcat T40.180SLP Telehandler w/Man Platform", "tag": "Maisto", "image": "maisto_000002.webp" },
	{ "name": "Porsche 918 Spyder", "tag": "Matchbox", "image": "matchbox_094568.webp" },
	{ "name": "MBX EV School Bus", "tag": "Matchbox", "image": "matchbox_754667.webp" },
	{ "name": "Scania P 360 Fire Engine", "tag": "Matchbox", "image": "matchbox_847577.webp" },
	{ "name": "Radical SR3 XXR", "tag": "Matchbox", "image": "matchbox_893464.webp" },
	{ "name": "1992 Mazda Autozam AZ-1", "tag": "Matchbox", "image": "matchbox_945677.webp" },
	{ "name": "Platelet", "tag": "Nendoroid", "image": "nendoroid_1036.webp" },
	{ "name": "Schwi", "tag": "Nendoroid", "image": "nendoroid_1090.webp" },
	{ "name": "Emma", "tag": "Nendoroid", "image": "nendoroid_1092.webp" },
	{ "name": "Aoi Inuyama", "tag": "Nendoroid", "image": "nendoroid_1097.webp" },
	{ "name": "Rika Takarada", "tag": "Nendoroid", "image": "nendoroid_1106.webp" },
	{ "name": "Light 2.0", "tag": "Nendoroid", "image": "nendoroid_1160.webp" },
	{ "name": "Rei Ayanami", "tag": "Nendoroid", "image": "nendoroid_1197.webp" },
	{ "name": "L 2.0", "tag": "Nendoroid", "image": "nendoroid_1200.webp" },
	{ "name": "Asuka Shikinami Langley", "tag": "Nendoroid", "image": "nendoroid_1202.webp" },
	{ "name": "Red Blood Cell", "tag": "Nendoroid", "image": "nendoroid_1214.webp" },
	{ "name": "Houshou Marine", "tag": "Nendoroid", "image": "nendoroid_1687.webp" },
	{ "name": "Gawr Gura", "tag": "Nendoroid", "image": "nendoroid_1688.webp" },
	{ "name": "Usada Pekora", "tag": "Nendoroid", "image": "nendoroid_1823.webp" },
	{ "name": "Korone Inugami", "tag": "Nendoroid", "image": "nendoroid_1861.webp" },
	{ "name": "Douki-chan", "tag": "Nendoroid", "image": "nendoroid_1921.webp" },
	{ "name": "Hitori Gotoh", "tag": "Nendoroid", "image": "nendoroid_2069.webp" },
	{ "name": "Amelia Watson", "tag": "Nendoroid", "image": "nendoroid_2216.webp" },
	{ "name": "Jollibee", "tag": "Nendoroid", "image": "nendoroid_2697.webp" },
	{ "name": "Momo Ayase", "tag": "Nendoroid", "image": "nendoroid_2701.webp" },
	{ "name": "Okarun", "tag": "Nendoroid", "image": "nendoroid_2702.webp" },
	{ "name": "Ken Kaneki", "tag": "Nendoroid", "image": "nendoroid_2734.webp" },
	{ "name": "Serval", "tag": "Nendoroid", "image": "nendoroid_752.webp" },
	{ "name": "Alpaca Suri", "tag": "Nendoroid", "image": "nendoroid_844.webp" },
	{ "name": "Japanese Crested Ibis", "tag": "Nendoroid", "image": "nendoroid_857.webp" },
	{ "name": "Zero Two", "tag": "Nendoroid", "image": "nendoroid_952.webp" },
	{ "name": "White Blood Cell (Neutrophil)", "tag": "Nendoroid", "image": "nendoroid_979.webp" },
	{ "name": "BIG BOY LOCOMOTIVE", "tag": "Nifeliz", "image": "nf10263.webp" },
	{ "name": "DDA40X LOCOMOTIVE", "tag": "Nifeliz", "image": "nf10296.webp" },
	{ "name": "Audi R8 V10", "tag": "RMZ City", "image": "rmz_city_985767.webp" },
	{ "name": "TOMICA No.13 NISSAN GT-R NISMO GT500", "tag": "Tomica", "image": "tomica_102618.webp" },
	{ "name": "TOMICA No.57 McLaren 720S", "tag": "Tomica", "image": "tomica_102632.webp" },
	{ "name": "TOMICA No.113 Toyota HIACE", "tag": "Tomica", "image": "tomica_102786.webp" },
	{ "name": "tomica PREMIUM 31 F40", "tag": "Tomica", "image": "tomica_131847.webp" },
	{ "name": "TOMICA No.70 LAMBORGHINI AVENTADOR SVJ", "tag": "Tomica", "image": "tomica_132134.webp" },
	{ "name": "TOMICA No.25 HITACHI LOADING SHOVEL EX8000-7", "tag": "Tomica", "image": "tomica_158264.webp" },
	{ "name": "TOMICA No.38 Audi R8 Coupé", "tag": "Tomica", "image": "tomica_158660.webp" },
	{ "name": "LONG TOMICA No.144 HINO PROFIA TRAILER / NISSAN CONTAINER", "tag": "Tomica", "image": "tomica_160830.webp" },
	{ "name": "LONG TOMICA No.145 NAGOYA CITY FIRE BUREAU LADDER TRUCK M32L-AT", "tag": "Tomica", "image": "tomica_160908.webp" },
	{ "name": "LONG TOMICA No.150 MITSUBISHI FUSO SUPER GREAT FISHING BOAT TRANSPORTER", "tag": "Tomica", "image": "tomica_173823.webp" },
	{ "name": "TOMICA No.11 LAMBORGHINI HURACÁN STO", "tag": "Tomica", "image": "tomica_174783.webp" },
	{ "name": "LONG TOMICA No.147 UD TRUCKS Quon TRAILER DUMP", "tag": "Tomica", "image": "tomica_175667.webp" },
	{ "name": "TOMICA No.37 BUGATTI CHIRON PUR SPORT", "tag": "Tomica", "image": "tomica_175759.webp" },
	{ "name": "tomica PREMIUM 33 FERRARI FXX K", "tag": "Tomica", "image": "tomica_179153.webp" },
	{ "name": "TOMICA No.91 CHEVROLET® CORVETTE®", "tag": "Tomica", "image": "tomica_188063.webp" },
	{ "name": "TOMICA No.74 LAMBORGHINI Countach LPI 800-4", "tag": "Tomica", "image": "tomica_188131.webp" },
	{ "name": "TOMICA No.57 ART MOVING COMPANY TRUCK", "tag": "Tomica", "image": "tomica_188407.webp" },
	{ "name": "TOMICA No.78 Honda CIVIC TYPE R", "tag": "Tomica", "image": "tomica_188728.webp" },
	{ "name": "TOMICA No.46 FERRARI DAYTONA SP3", "tag": "Tomica", "image": "tomica_188865.webp" },
	{ "name": "TOMICA No.64 Toyota VOXY", "tag": "Tomica", "image": "tomica_188919.webp" },
	{ "name": "LONG TOMICA No.127 MITSUBISHI FUSO SUPER GREAT CONCRETE PUMPING TRUCK", "tag": "Tomica", "image": "tomica_189381.webp" },
	{ "name": "TOMICA (LONG TYPE) No.121 ICHIHARA CITY FIRE BUREAU SCRUM FORCE", "tag": "Tomica", "image": "tomica_189398.webp" },
	{ "name": "TOMICA (LONG TYPE) No.135 ＮＸ NIPPON EXPRESS TRAILER", "tag": "Tomica", "image": "tomica_189404.webp" },
	{ "name": "tomica PREMIUM No.07 Lamborghini Essenza SCV12", "tag": "Tomica", "image": "tomica_212355.webp" },
	{ "name": "TOMICA LONG No.149 HRC MOTOR HOME", "tag": "Tomica", "image": "tomica_228035.webp" },
	{ "name": "TOMICA No.89 MOUNTAIN RESCUE VEHICLE", "tag": "Tomica", "image": "tomica_228189.webp" },
	{ "name": "TOMICA No.17 ISUZU ELF ROAD RAILER", "tag": "Tomica", "image": "tomica_228233.webp" },
	{ "name": "TOMICA No.60 NISSAN GT-R NISMO", "tag": "Tomica", "image": "tomica_228455.webp" },
	{ "name": "TOMICA No.94 NISSAN SERENA", "tag": "Tomica", "image": "tomica_228554.webp" },
	{ "name": "TOMICA(LONG TYPE) No.142 ISUZU GIGA HEAVY CONSTRUCTION MACHINERY TRANSPORTER", "tag": "Tomica", "image": "tomica_228639.webp" },
	{ "name": "TOMICA (LONG TYPE) NO.136 UD TRUCKS Quon TANK LORRY", "tag": "Tomica", "image": "tomica_228653.webp" },
	{ "name": "TOMICA (LONG TYPE) NO.129 ISUZU ERGA OSAKA CITY BUS", "tag": "Tomica", "image": "tomica_228660.webp" },
	{ "name": "TOMICA No.88 NISSAN FAIRLADY Z NISMO", "tag": "Tomica", "image": "tomica_229261.webp" },
	{ "name": "TOMICA LONG No.144-5 ISUZU GIGA SUPER AMBULANCE'25", "tag": "Tomica", "image": "tomica_270072.webp" },
	{ "name": "tomica PREMIUM No.5 Lamborghini Murciélago", "tag": "Tomica", "image": "tomica_297895.webp" },
	{ "name": "TOMICA No.65 HITACHI DOUBLE ARM WORKING MACHINE ASTACO", "tag": "Tomica", "image": "tomica_333654.webp" },
	{ "name": "TOMICA Hitachi Rigid Dump Truck EH3500ACⅡ | Takara Tomy", "tag": "Tomica", "image": "tomica_333678.webp" },
	{ "name": "LONG TOMICA No.131 MITSUBISHI FUSO SUPER GREAT TRANSPORTER", "tag": "Tomica", "image": "tomica_334088.webp" },
	{ "name": "TOMICA No.73 KOBELCO ROUGH TERRAIN CRANE PANTHER-X 250", "tag": "Tomica", "image": "tomica_392354.webp" },
	{ "name": "LONG TOMICA No.134 Mercedes-Benz CITARO KEISEI ARTICULATED BUS", "tag": "Tomica", "image": "tomica_395720.webp" },
	{ "name": "TOMICA No.9 KOMATSU EXCAVATOR PC200-10", "tag": "Tomica", "image": "tomica_439172.webp" },
	{ "name": "TOMICA No. 29 Thomas Land Express", "tag": "Tomica", "image": "tomica_450967.webp" },
	{ "name": "DREAM TOMICA No.145 INITIAL D AE86 TRUENO", "tag": "Tomica", "image": "tomica_486466.webp" },
	{ "name": "Tomica No. 80 Propane Gas Deliverly Truck", "tag": "Tomica", "image": "tomica_625689.webp" },
	{ "name": "No. 0112 Nissan Diesel Quon Tank Lorry (ENEOS)", "tag": "Tomica", "image": "tomica_726269.webp" },
	{ "name": "TOMICA No.45 Toyota DYNA REFUSE TRUCK", "tag": "Tomica", "image": "tomica_741374.webp" },
	{ "name": "TOMICA No.53 NISSAN DIESEL Quon MIXER CAR", "tag": "Tomica", "image": "tomica_742241.webp" },
	{ "name": "TOMICA No.71 Hitachi Construction Machinery WHEEL LOADER ZW220", "tag": "Tomica", "image": "tomica_742319.webp" },
	{ "name": "TOMICA No.69 AQUARIUM TRUCK", "tag": "Tomica", "image": "tomica_746829.webp" },
	{ "name": "TOMICA No.51 TOYOTA CROWN COMFORT TAXI", "tag": "Tomica", "image": "tomica_746881.webp" },
	{ "name": "TOMICA No.63 MAEDA SEISAKUSHO MINI CRAWLER CRANE", "tag": "Tomica", "image": "tomica_746928.webp" },
	{ "name": "TOMICA No.116 SUPER AMBULANCE", "tag": "Tomica", "image": "tomica_785439.webp" },
	{ "name": "TOMICA No.56 KOMATSU BULLDOZER D155AX-6", "tag": "Tomica", "image": "tomica_785538.webp" },
	{ "name": "LONG TOMICA No.139 CATTLE TRANSPORTER", "tag": "Tomica", "image": "tomica_798323.webp" },
	{ "name": "TOMICA No.49 Toyota COASTER KINDERGARTEN BUS", "tag": "Tomica", "image": "tomica_799207.webp" },
	{ "name": "TOMICA No.118 LAMBORGHINI VENENO", "tag": "Tomica", "image": "tomica_801290.webp" },
	{ "name": "TOMICA No.12 Toyota ALPHARD", "tag": "Tomica", "image": "tomica_824848.webp" },
	{ "name": "Tomica No. 87 Lamborghini Aventador LP 700-4 Dubai Police Car", "tag": "Tomica", "image": "tomica_826403.webp" },
	{ "name": "Long Tomica No. 142 Subaru Sambar Kitchen Trailer", "tag": "Tomica", "image": "tomica_837373.webp" },
	{ "name": "LONG TOMICA No.130 KOBELCO CONSTRUCTION MACHINERY BUILDINGS DEMOLITION MACHINE SK3500D", "tag": "Tomica", "image": "tomica_858270.webp" },
	{ "name": "TOMICA No.42 HATO BUS", "tag": "Tomica", "image": "tomica_859420.webp" },
	{ "name": "TOMICA No.82 Toyota SORA", "tag": "Tomica", "image": "tomica_859420.webp" },
	{ "name": "TOMICA No.101 ISUZU GIGA DUMP TRUCK", "tag": "Tomica", "image": "tomica_859864.webp" },
	{ "name": "TOMICA No.111 TOYOTA L&F GENEO", "tag": "Tomica", "image": "tomica_859918.webp" },
	{ "name": "LONG TOMICA No.125 ISUZU GIGA WOOD TRANSPOTER", "tag": "Tomica", "image": "tomica_879541.webp" },
	{ "name": "TOMICA No.7 Mercedes-AMG GT R", "tag": "Tomica", "image": "tomica_879602.webp" },
	{ "name": "TOMICA No.20 ISUZU ERGA TOEI BUS", "tag": "Tomica", "image": "tomica_879718.webp" },
	{ "name": "LONG TOMICA No.122 MITSUBISHI FUSO SUPER GREAT SINKANSEN SERIES H5 HAYABUSA TRANSPORTER", "tag": "Tomica", "image": "tomica_880431.webp" },
	{ "name": "TOMICA (Asia Original) AO-02 ISUZU ELF VEHICLE TRANSPORTER", "tag": "Tomica", "image": "tomica_903963.webp" },
	{ "name": "TOMICA (Asia Original) AO-08 LAMBORGHINI REVENTON", "tag": "Tomica", "image": "tomica_904021.webp" },
	{ "name": "TOMICA No.120 Honda CIVIC TYPE R Race Control Car", "tag": "Tomica", "image": "tomica_917113.webp" },
	{ "name": "TOMICA No.107 LAMBORGHINI REVUELTO", "tag": "Tomica", "image": "tomica_917144.webp" },
	{ "name": "TOMICA No.34 ISUZU ELF", "tag": "Tomica", "image": "tomica_917342.webp" },
	{ "name": "TOMICA No.31 UD TRUCKS Quon", "tag": "Tomica", "image": "tomica_917595.webp" },
	{ "name": "TOMICA No.143 Hitachi Construction Machinery Super Long Front Excavator ZX210-7 SLF and Transporter", "tag": "Tomica", "image": "tomica_917694.webp" },
	{ "name": "tomica PREMIUM No.20 ENZO FERRARI", "tag": "Tomica", "image": "tomica_930426.webp" },
	{ "name": "TOMICA No. 87 SPRINKLER TRUCK", "tag": "Tomica", "image": "tomica_934577.webp" },
	{ "name": "Lamborghini Centenario Roadster", "tag": "Tomica", "image": "tomica_944133.webp" },
	{ "name": "Dream Tomica No. 141 Super Sonic Runner", "tag": "Tomica", "image": "tomica_947859.webp" },
	{ "name": "TOMICA No.117-09 Suzuki Super Carry '25", "tag": "Tomica", "image": "tomica_950608.webp" },
	{ "name": "TOMICA No.18 NISSAN NV350 CARAVAN AMBULANCE", "tag": "Tomica", "image": "tomica_950608.webp" },
	{ "name": "tomica PREMIUM41 TESLA CYBERTRUCK'25", "tag": "Tomica", "image": "tomica_955375.webp" },
	{ "name": "Tomica No. 107 Lexus IS F CCS-R", "tag": "Tomica", "image": "tomica_968451.webp" },
	{ "name": "TOMICA No.85 MITSUBISHI FUSO SUPER GREAT", "tag": "Tomica", "image": "tomica_971986.webp" },
	{ "name": "Tomica No. 72 Lotus Elise Sport 220 II (Special First Edition)", "tag": "Tomica", "image": "tomica_972356.webp" },
	{ "name": "LONG TOMICA No.132 YOKOHAMA CITY FIRE BUREAU SUPER RANGER MOBILITY TOWING WORK VEHICLE", "tag": "Tomica", "image": "tomica_981695.webp" },
	{ "name": "LONG TOMICA No.128 NAHA FIRE DEPARTMENT HYPER MIST BLOWER", "tag": "Tomica", "image": "tomica_981787.webp" },
	{ "name": "NISSAN GT-R EARTH GRANNER PROMO", "tag": "Tomica", "image": "tomica_985679.webp" },
	{ "name": "Tomica No. 60 Nissan GT-R Nismo", "tag": "Tomica", "image": "tomica_987456.webp" },
	{ "name": "TOMICA PRM TOYOTA ALPHARD'25", "tag": "Tomica", "image": "tomica_955740.webp" },
	{ "name": "tomica PREMIUM 01 TOMICA SKYLINE TURBO SUPER SILHOUETTE", "tag": "Tomica", "image": "tomica_123767.webp" },
	{ "name": "tomica PREMIUM No.29 MAZDA SAVANNA RX-7 (SA22C)", "tag": "Tomica", "image": "tomica_297987.webp" },
	{ "name": "Premium RS Nissan Skyline GT-R V·specⅡ Nür | Takara Tomy", "tag": "Tomica", "image": "tomica_130895.webp" },
	{ "name": "tomica PREMIUM No.40 Toyota MR2", "tag": "Tomica", "image": "tomica_297796.webp" },
	{ "name": "tomica PREMIUM No.15 NISSAN FAIRLADY Z (Z31)", "tag": "Tomica", "image": "tomica_936374.webp" },
	{ "name": "tomica PREMIUM No.33 Lamborghini Countach LP 400", "tag": "Tomica", "image": "tomica_933908.webp" },
].forEach(i =>{
	const cell = document.createElement("span");
	cell.dataset.type = "cell";
	cell.dataset.tag = i.tag.toLowerCase().replaceAll(" ", "_");
	
	const img = document.createElement("img");
	img.src = `https://raw.githubusercontent.com/CodanRaigen21/Voxelite/main/images/${i.image}`;
	cell.appendChild(img);
	
	const name = document.createElement("h3");
	name.textContent = i.name;
	cell.appendChild(name);
	
	const tag = document.createElement("span");
	tag.dataset.type = "tag";
	tag.textContent = i.tag;
	cell.appendChild(tag);
	
	shelf.appendChild(cell);
});

const tags = document.querySelectorAll(`[data-holds="tag"] span`);
const cells = document.querySelectorAll(`span[data-type="cell"]`);
tags.forEach(i =>{
	i.addEventListener("click", e =>{ tags.forEach(j => j.classList.remove("selected")); i.classList.add("selected"); if(i.dataset.tag === "all"){ 	cells.forEach(j => j.style.display = "block"); } else{ 	document.querySelectorAll(`span[data-type="cell"]:not([data-tag="${i.dataset.tag}"])`).forEach(j => j.style.display = "none"); 	document.querySelectorAll(`span[data-type="cell"][data-tag="${i.dataset.tag}"]`).forEach(j => j.style.display = "block"); } });
});

const searchBar = document.getElementById("search");
searchBar.addEventListener("keydown", e =>{
	if(e.keyCode === 13){ tags.forEach(j => j.classList.remove("selected")); const contentName = document.querySelectorAll("h3"); let filter = searchBar.value.toUpperCase(); for(var z = 0; z < contentName.length; z++){ 	mainValue = contentName[z].textValue || contentName[z].innerText; 	if(mainValue.toUpperCase().indexOf(filter) > -1){ cells[z].style.display="block"; } 	else{ cells[z].style.display="none"; } } }
});
